package com.ifcolab.safesoft.view;

import com.ifcolab.safesoft.controller.RelatorioController;
import com.ifcolab.safesoft.model.Servico;
import com.ifcolab.safesoft.model.Item;
import com.ifcolab.safesoft.model.Relatorio;

import javax.swing.JOptionPane;


public class DlgRelatorio extends javax.swing.JDialog {

    private final RelatorioController controller;
    private boolean relatorioSalvo = false;
    
    
    public DlgRelatorio(java.awt.Frame parent, boolean modal, Servico servico, Item item) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.controller = new RelatorioController(servico, item);
        
        configurarInterface();
        carregarRelatorioExistente();
    }
    
    private void configurarInterface() {
        configurarCamposTexto();
        preencherInformacoesItem();
    }
    
    private void configurarCamposTexto() {
        txtResultado.setLineWrap(true);
        txtResultado.setWrapStyleWord(true);
        txtObservacoes.setLineWrap(true);
        txtObservacoes.setWrapStyleWord(true);
    }
    
    private void preencherInformacoesItem() {
        lblItem.setText("Item: " + controller.getTipoItem());
        lblCliente.setText("Cliente: " + controller.getNomeCliente());
        lblTecnico.setText("Tecnico: " + controller.getNomeTecnico());
        lblData.setText("Data: " + controller.getDataHoraFormatada());
    }
    
    private void carregarRelatorioExistente() {
        try {
            Relatorio relatorioAtual = controller.buscarRelatorioDaServico();
            if (relatorioAtual != null) {
                preencherFormulario(relatorioAtual);
            }
        } catch (Exception e) {
            exibirErro("Erro ao carregar relatório existente", e);
        }
    }
    
    private void preencherFormulario(Relatorio relatorio) {
        txtResultado.setText(relatorio.getResultado());
        txtObservacoes.setText(relatorio.getObservacoes());
        lblTitleGerenciaTecnicos.setText("Editar Relatório");
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String resultado = txtResultado.getText().trim();
            String observacoes = txtObservacoes.getText().trim();
            
            controller.validarESalvarRelatorio(resultado, observacoes);
            
            relatorioSalvo = true;
            exibirSucesso("Relatório salvo com sucesso!");
            dispose();
        } catch (Exception e) {
            exibirErro("Erro ao salvar relatório", e);
            if (e.getMessage().contains("Resultado")) {
                txtResultado.requestFocus();
            }
        }
    }
    
    private void btnAbrirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Relatorio relatorioAtual = controller.buscarRelatorioDaServico();
            if (relatorioAtual == null) {
                JOptionPane.showMessageDialog(this, 
                    "Não há relatório salvo para esta consulta.", 
                    "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            controller.abrirPdf(relatorioAtual);
        } catch (Exception e) {
            exibirErro("Erro ao abrir relatório", e);
        }
    }
    
    private void exibirSucesso(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem, "Sucesso", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void exibirErro(String mensagem, Exception e) {
        JOptionPane.showMessageDialog(this, 
            mensagem + ": " + e.getMessage(), 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
    }
    
    public boolean isRelatorioSalvo() {
        return relatorioSalvo;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblItem = new javax.swing.JLabel();
        lblObservacoes = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblTecnico = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnAbrirRelatorio = new com.ifcolab.safesoft.components.SecondaryCustomButton();
        btnSalvar = new com.ifcolab.safesoft.components.PrimaryCustomButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new com.ifcolab.safesoft.components.CustomTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new com.ifcolab.safesoft.components.CustomTextArea();
        tmRecepcionistas = new javax.swing.JScrollPane();
        grdRecepcionistas = new com.ifcolab.safesoft.components.CustomTable();
        lblSubtituloGerenciaTecnicos = new javax.swing.JLabel();
        lblTitleGerenciaTecnicos = new javax.swing.JLabel();
        lblBackgroundTabela = new javax.swing.JLabel();
        lblBackgroundCadastro = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 870));
        getContentPane().setLayout(null);

        lblItem.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblItem);
        lblItem.setBounds(70, 90, 850, 20);

        lblObservacoes.setForeground(new java.awt.Color(51, 51, 51));
        lblObservacoes.setText("Observações");
        getContentPane().add(lblObservacoes);
        lblObservacoes.setBounds(700, 370, 160, 20);

        lblCliente.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblCliente);
        lblCliente.setBounds(70, 130, 820, 20);

        lblTecnico.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblTecnico);
        lblTecnico.setBounds(70, 180, 660, 20);

        lblData.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblData);
        lblData.setBounds(70, 230, 960, 20);

        lblResultado.setForeground(new java.awt.Color(51, 51, 51));
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(70, 370, 160, 20);

        btnAbrirRelatorio.setText("Abrir Relatorio");
        btnAbrirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirRelatorio);
        btnAbrirRelatorio.setBounds(260, 298, 190, 30);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(50, 298, 180, 30);

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(690, 390, 590, 390);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 390, 590, 390);

        grdRecepcionistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tmRecepcionistas.setViewportView(grdRecepcionistas);

        getContentPane().add(tmRecepcionistas);
        tmRecepcionistas.setBounds(40, 366, 1260, 420);

        lblSubtituloGerenciaTecnicos.setFont(new java.awt.Font("Fira Sans Medium", 0, 13)); // NOI18N
        lblSubtituloGerenciaTecnicos.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloGerenciaTecnicos.setText("Organize as informações do item, adicionando resultados e observações");
        getContentPane().add(lblSubtituloGerenciaTecnicos);
        lblSubtituloGerenciaTecnicos.setBounds(30, 40, 650, 17);

        lblTitleGerenciaTecnicos.setFont(new java.awt.Font("Fira Sans SemiBold", 0, 18)); // NOI18N
        lblTitleGerenciaTecnicos.setForeground(new java.awt.Color(51, 51, 51));
        lblTitleGerenciaTecnicos.setText("Cadastrar Relatorio");
        getContentPane().add(lblTitleGerenciaTecnicos);
        lblTitleGerenciaTecnicos.setBounds(30, 20, 210, 22);

        lblBackgroundTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundTableModel.png"))); // NOI18N
        getContentPane().add(lblBackgroundTabela);
        lblBackgroundTabela.setBounds(-10, 330, 1350, 500);

        lblBackgroundCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgroundCrud.png"))); // NOI18N
        getContentPane().add(lblBackgroundCadastro);
        lblBackgroundCadastro.setBounds(-10, 60, 1330, 290);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        lblBackground.setText("jLabel3");
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1350, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ifcolab.safesoft.components.SecondaryCustomButton btnAbrirRelatorio;
    private com.ifcolab.safesoft.components.PrimaryCustomButton btnSalvar;
    private com.ifcolab.safesoft.components.CustomTable grdRecepcionistas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBackgroundCadastro;
    private javax.swing.JLabel lblBackgroundTabela;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSubtituloGerenciaTecnicos;
    private javax.swing.JLabel lblTitleGerenciaTecnicos;
    private javax.swing.JScrollPane tmRecepcionistas;
    private com.ifcolab.safesoft.components.CustomTextArea txtObservacoes;
    private com.ifcolab.safesoft.components.CustomTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
